### ISSUE TITLE
[Bug] When creating student, On backend a role of student is getting added with some default validity

### ISSUE THREAD

**Issue by rishigupta1109** [Iitpulse/client#167]
This bug is creating ambuiguity which is needed to be discussed and should be resolved accordingly
![image](https://github.com/Iitpulse/client/assets/84670640/9e0cc822-02a0-4d0d-ac42-922d3abddeab)

**Comment by Anuragtech02** [comment]
Yes this is correct, the student role is valid till the batch only, later the validity can be extended by the admin

**Comment by rishigupta1109** [comment]
So that would be ambiguios for our backend that two same roles are present with different validity. IG We should hide the student role from UI or check in backend that its already present or not.
