### ISSUE TITLE
Login page UI changes and Error Handling

### ISSUE THREAD

**Issue by rishigupta1109** [Iitpulse/client#41]
- [x]  The user should not go back to log in on clicking the back button
- [x]  Login page UI
    - [x]  Error handling
    - [x]  Show/Hide Password
    - [x] Loading in questions
    - [x] icon fix (print and export to csv)
    - [x] remove id and shift preview in ques to left

**Comment by Anuragtech02** [comment]
Also check on login page if the user is logged in 
You can check for `currentUser` it's coming from `AuthContext`
If the user exists navigate to `/` or home.

**Comment by rishigupta1109** [comment]
done.
